sudo: false
language: java
jdk: oraclejdk8
cache:
  directories:
   - $HOME/.m2
   - $HOME/.cache/pip
   - $HOME/conda
   - $HOME/.sonar/cache
before_install:
  - if [ ! -e $HOME/conda/bin/activate ]; then
    wget -nc https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
    bash Miniconda3-latest-Linux-x86_64.sh -f -b -p $HOME/conda;
    fi
  - source $HOME/conda/bin/activate root
  - conda install -y -q -c rdkit -c 3d-e-Chem sygma pandas protobuf
install:
- mvn package -B
script: xvfb-run mvn verify -B
after_success:
 - mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN

