# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    types:
      - "opened"
      - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        activate-environment: test
        python-version: 3.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF', 'targetplatform/*.target') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Cache conda deps
      uses: actions/cache@v2
      with:
        path: |
          ~/conda_pkgs_dir
          ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/build.yml') }}
        restore-keys: ${{ runner.os }}-pip
    - name: OS dependencies
      run: sudo apt-get install xvfb
    - name: Conda dependencies
      run: conda install -y -q -c conda-forge pip wheel rdkit pandas protobuf
    - name: Python dependencies
      run: pip install sygma
    - name: Build with Maven
      run: mvn -B package
    - name: Run tests
      run: xvfb-run mvn verify -B
    - name: Set up JDK 11 for SonarCloud analysis
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: SonarCloud analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn sonar:sonar
