# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
    types:
      - "opened"
      - "reopened"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup miniconda
      uses: conda-incubator/setup-miniconda@v2
    # - name: Cache deps
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.m2
    #       ~/.cache/pip
    #       ~/conda_pkgs_dir
    #       ~/.sonar/cache
    #     key: ${{ runner.os }}-${{ hashFiles('.github/workflows/build.yml') }}
    - name: OS dependencies
      run: sudo apt-get install xvfb
    - name: Conda dependencies
      run: conda install -y -q -c conda-forge rdkit pandas protobuf
    - name: Python dependencies
      run: pip install sygma
    - name: Build with Maven
      run: mvn -B package
    - name: Run tests
      run: xvfb-run mvn verify -B
    - name: SonarCloud analysis
      run: mvn sonar:sonar -Dsonar.login=$SONAR_TOKEN
